#!/bin/bash
# This bash script is an alternative to the java credential helper.
# In order to use this script, chmod +x and put it on the $PATH
# This script leverages oci raw-request and supports all principal types.

if [[ "$#" -ne 1 || "$1" != "get" ]]; then
  echo "Usage: docker-credential-ocir get" 1>&2
  exit 1
fi

read rawUrl;

if [[ $rawUrl == https://* ]]; then
  registryUrl=`echo $rawUrl | cut -c 9-`
else
  registryUrl="$rawUrl"
fi

targetUri="https://$registryUrl/20180419/docker/token"

token=`oci raw-request --http-method GET --target-uri $targetUri | jq -r .data.token`

jq -n --arg rawUrl "$rawUrl" --arg token "$token" '{"ServerURL":$rawUrl,"Username":"BEARER_TOKEN","Secret":$token}'
